language: go
arch:
    - amd64
    - ppc64le
sudo: false

go_import_path: go.uber.org/zap
env:
  global:
    - TEST_TIMEOUT_SCALE=10
    - GO111MODULE=on

matrix:
  include:
  - go: 1.13.x
  - go: 1.14.x
    env: LINT=1
# Adding code to run on  power systems    
  - arch: ppc64le
    go: 1.13.x    
  - arch: ppc64le
    go: 1.14.x
    env: LINT=1
      

script:
  - test -z "$LINT" || make lint
  - make test
  - make bench

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
